### ISSUE TITLE
The list hasn't been maintained for a while

### ISSUE THREAD

**Issue by YogliB** [CalvinWalzel/awesome-svelte#10]
If it's a time issue, I'll be happy to help.

**Comment by CalvinWalzel** [comment]
Hey YogliB,

Thanks for your concern about my activity in this repository. I'm currently in the process of buying a house, which is eating a lot of time. I reviewed all open PRs and I'll try to check this repository more often from now on again :)

**Comment by YogliB** [comment]
@CalvinWalzel

Thanks for your reply, and thanks for this repo :)
