### ISSUE TITLE
Official Template working in VSCode with prettier, eslint

### ISSUE THREAD

**Issue by SteveALee** [CalvinWalzel/awesome-svelte#38]
I found the official template didn't work with VS code extensions for prettier and eslint  but eventually got things working after much "sweat and tears" in this [svelte-code-cypress-project template](https://github.com/SteveALee/svelte-code-cypress-project). The readme has details of open issues addressed.

I also added Cypress for testing

I would had offered a PR but there's not an obvious section for templates/

**Comment by sw-yx** [comment]
this one has a lot of tempaltes https://github.com/ryanatkn/awesome-svelte-resources, try PR there

**Comment by SteveALee** [comment]
@sw-yx Ok thanks - I hadn't realised there was more than one svelte-awesome - probably not ideal.

looks like osmeone added it there already! ;)

Cheers!
