### ISSUE TITLE
merge into sveltejs/community?

### ISSUE THREAD

**Issue by sw-yx** [CalvinWalzel/awesome-svelte#39]
Hey Calvin! thanks for the awesome list!

we just got going with https://github.com/sveltejs/community/ and would like to offer a place for community resources like this. shared maintainership would be cool too. just figured i'd open that suggestion, ofc there is value to keeping your own, selective list, too.

**Comment by CalvinWalzel** [comment]
Hey swyx,

Thanks for your message. I don't really have time to maintain this list at the moment, so I'd be happy to point it towards the official repository you mentioned.

Upon closer inspection I see that the repository currently only contains events & "resources" (but no actual libraries & tools?). Is that something the svelte team intends to change in the future?

**Comment by sw-yx** [comment]
we actually have libraries and tools! i guess we just call it the Code section https://svelte-community.netlify.com/

**Comment by himynameisdave** [comment]
Hi @CalvinWalzel! I would love to see some movement on this. Perhaps we could archive this repo and add a note pointing to `sveltejs/community` instead, much like this other [`ryanatkn/awesome-svelte-resources`](https://github.com/ryanatkn/awesome-svelte-resources) list is doing? Let me know if you need a hand!

**Comment by sw-yx** [comment]
ya. trying to help the community come together. slow and steady, hahah

**Comment by CalvinWalzel** [comment]
@himynameisdave Done! :) Sorry for the long delay.
